# Variables
[env]
PROJECT_DIR={ script = ["pwd"] }
CROSS_CC="arm-none-eabi-gcc"
# Disable color codes in env_logger
RUST_LOG_STYLE="never"

[tasks.unsupported]
script_runner="@shell"
script='''
echo "Qemu fuzzer not supported on windows"
'''

[tasks.build]
linux_alias = "build_unix"
mac_alias = "build_unix"
windows_alias = "unsupported"

[tasks.build_unix]
command = "cargo"
args = ["build", "--release"]

# Run the fuzzer
[tasks.run]
linux_alias = "run_unix"
mac_alias = "run_unix"
windows_alias = "unsupported"

[tasks.run_unix]
env = { "RUST_LOG" = "off" }
command = "cargo"
args = [
    "run", "--release",
    "--",
    "${@}",
]
dependencies = [ "build" ]

# Test/debug the fuzzer
[tasks.test]
linux_alias = "test_unix"
mac_alias = "test_unix"
windows_alias = "unsupported"

[tasks.test_unix]
clear = true
env = { "RUST_LOG" = "debug" }
command = "cargo"
args = [
    "run", "--release",
    "--",
    "${@}",
]
dependencies = [ "build" ]

# Performance measurements
[tasks.perf]
linux_alias = "perf_unix"
mac_alias = "perf_unix"
windows_alias = "unsupported"

[tasks.perf_unix]
env = { "RUST_LOG" = "off" }
command = "cargo"
args = [
    "run", "--release",
    "--features", "performance",
    "--",
    "${@}",
]
dependencies = [ "build" ]

# Clean up
[tasks.clean]
linux_alias = "clean_unix"
mac_alias = "clean_unix"
windows_alias = "unsupported"

[tasks.clean_unix]
# Disable default `clean` definition
clear = true
script_runner="@shell"
script='''
cargo clean
rm -rf runs/
'''


# Test/debug the fuzzer
[tasks.debug]
linux_alias = "debug_unix"
mac_alias = "debug_unix"
windows_alias = "unsupported"

[tasks.debug_unix]
env = { "RUST_LOG" = "debug" }
command = "rust-lldb"
args = [
    "target/release/aspfuzz",
    "--",
    "${@}",
]
dependencies = [ "build" ]